version: "3"
services:
  dev:
    image: elastic-buddy
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      KIBANA_HOSTS: "http://kibana:5601"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: [./scripts/wait-for-elasticsearch]
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - elastic-buddy

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elastic-buddy-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - http.port=9200
      - discovery.type=single-node
    ports:
      - 9200:9200
    hostname: 'elasticsearch'
    networks:
      - elastic-buddy

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    networks:
      - elastic-buddy

networks:
  elastic-buddy:
    driver: bridge
