#!/bin/bash
trap "docker-compose down --volumes --remove-orphans" 0
docker-compose down --volumes --remove-orphans

echo "--- Provisioning dev environment container..."
docker-compose build

docker-compose run --rm dev "npm install"

docker-compose run --rm dev "${@-bash}"
