#!/bin/bash -e

are-local-dependencies-up ()
{
  curl -X GET $ELASTICSEARCH_HOSTS > /dev/null
  es_verifier=$?
  # We don't need to check kibana because it's not needed
  # and by default it can only be accessed using localhost
  # curl -X GET $KIBANA_HOSTS > /dev/null
  # kibana_verifier=$?
  if [ 0 = $es_verifier ]
      then
          true
      else
          false
  fi
}


until are-local-dependencies-up;
do
  >&2 echo "ES is unavailable - waiting"
  sleep 1
done

>&2 echo "ES is up - moving on"

/bin/bash -c "$@"
